const baseUrl = "https://raw.githubusercontent.com/Agoric/documentation/agoric-slide-control/main/guides/";

const config = {
  Page_Introduction: baseUrl + "getting-started/intro-to-agoric.md",
  Page_Beginner: baseUrl + "getting-started/beginner.md",
  Page_Advanced: baseUrl + "getting-started/advanced.md",
  Page_Whats_New_in_Agoric: baseUrl + "getting-started/whats-new-in-agoric.md",
  Page_Tutorial_1: baseUrl + "getting-started/README.md",
  Page_Tutorial_2: baseUrl + "getting-started/tutorial-dapp-agoric-basics.md",
  Page_Tutorial_3: baseUrl + "getting-started/tutorial-dapp-orchestration.md",
  Page_How_What_is_Zoe: baseUrl + "zoe/README.md",
  Page_ERTP: baseUrl + "ertp/README.md",
  Page_Agoric_CLI: baseUrl + "agoric-cli/README.md",
  Page_How_to_Build_a_Client_UI: baseUrl + "getting-started/how-to-build-client-UI.md",
  Page_Permissioned_Deployments: baseUrl + "coreeval/README.md",
  Page_Testing: baseUrl + "getting-started/testing-a-dapp.md",
  Page_Debugging: baseUrl + "getting-started/debugging-a-dapp.md",
  Page_API_Reference: baseUrl + "getting-started/api_reference.md",
  Page_Lesson_1: baseUrl + "getting-started/startingAnAgoricChain.md",
  Page_Lesson_2: baseUrl + "getting-started/lesson02.md",
  Page_Lesson_3: baseUrl + "getting-started/lesson03.md",
  Page_Lesson_4: baseUrl + "getting-started/lesson04.md",
  Page_Lesson_5: baseUrl + "getting-started/lesson05.md",
  Page_Lesson_6: baseUrl + "getting-started/lesson06.md",
  Page_Lesson_7: baseUrl + "getting-started/lesson07.md",
  Page_Lesson_8: baseUrl + "getting-started/lesson08.md",
  Page_Lesson_9: baseUrl + "getting-started/lesson09.md",
  Page_Lesson_10: baseUrl + "getting-started/lesson10.md",
  Page_Lesson_11: baseUrl + "getting-started/lesson11.md",
  Page_Lesson_12: baseUrl + "getting-started/lesson12.md",
  Page_Lesson_13: baseUrl + "getting-started/lesson13.md",
  Page_Lesson_14: baseUrl + "getting-started/lesson14.md",
  Page_Lesson_15: baseUrl + "getting-started/lesson15.md",
  Page_Lesson_16: baseUrl + "getting-started/lesson16.md",
  Page_Discord: "https://www.discord.com",
  Page_Office_Hours: "https://agoric.com/office-hours/",
  Page_X: "https://x.com/agoric",

  Page_What_is_Agoric: baseUrl + "/placeholder.md",
  Page_Smart_Wallet_Dapp_Architecture: baseUrl + "/placeholder.md",
  Page_Signing_and_Broadcasting_Offers: baseUrl + "/placeholder.md",
  Page_Querying_VStorage: baseUrl + "/placeholder.md",
  Page_Specifying_Offers: baseUrl + "/placeholder.md",
  Page_Smart_Wallet_VStorage_Topics: baseUrl + "/placeholder.md",
  Page_VBank_Assets_and_Cosmos_Bank_Balances: baseUrl + "/placeholder.md",
  Page_Deploying_Smart_Contracts: baseUrl + "/placeholder.md",
  Page_Smart_Contract_Basics: baseUrl + "/placeholder.md",
  Page_Zoe_Overview: baseUrl + "/zoe/README.md",
  Page_What_is_Zoe: baseUrl + "/zoe/README.md",
  Page_Why_Use_Zoe: baseUrl + "/zoe/README.md",
  Page_Building_a_Contract: baseUrl + "/placeholder.md",
  Page_Contract_Installation: baseUrl + "/placeholder.md",
  Page_Starting_a_Contract_Instance: baseUrl + "/placeholder.md",
  Page_Trading_with_Offer_Safety: baseUrl + "/placeholder.md",
  Page_Contract_Upgrade: baseUrl + "/placeholder.md",

  Page_JavaScript_Framework: baseUrl + "/placeholder.md",
  Page_Wallet: baseUrl + "/placeholder.md",
  Page_Wallet_and_Agoric_Architecture: baseUrl + "/placeholder.md",
  Page_Wallet_Bridge_Protocol: baseUrl + "/placeholder.md",
  Page_Petnames_and_Paths: baseUrl + "/placeholder.md",
  Page_The_Agoric_Board: baseUrl + "/placeholder.md",
  Page_Wallet_UI: baseUrl + "/placeholder.md",
  Page_ERTP_Overview: baseUrl + "/placeholder.md",
  Page_ERTP_Concepts_Overview: baseUrl + "/placeholder.md",
  Page_Method_Naming_Structure: baseUrl + "/placeholder.md",
  Page_Life_of_Assets: baseUrl + "/placeholder.md",
  Page_Creating_and_Using_Non_Fungible_Assets: baseUrl + "/placeholder.md",
  Page_Amounts_Are_Not_Assets: baseUrl + "/placeholder.md",
  Page_Object_Capabilities_and_ERTP: baseUrl + "/placeholder.md",
  Page_Security_Properties: baseUrl + "/placeholder.md",
  Page_Promises: baseUrl + "/placeholder.md",
  Page_Amounts_Values_and_Brands: baseUrl + "/placeholder.md",
  Page_AmountMath: baseUrl + "/placeholder.md",
  Page_Issuers_and_Mints: baseUrl + "/placeholder.md",
  Page_Purses_and_Payments: baseUrl + "/placeholder.md",

  Page_Agoric_Platform: baseUrl + "/placeholder.md",
  Page_SwingSet: baseUrl + "/placeholder.md",
  Page_Cosmos_SDK: baseUrl + "/placeholder.md",
  Page_Dynamic_IBC: baseUrl + "/placeholder.md",
  Page_Tendermint: baseUrl + "/placeholder.md",
};

export default config;
